### ISSUE TITLE
bug when processing buffer

### ISSUE THREAD

**Issue by Mosuyun** [arielfri/buffr#1]
some raster works well while others return an error like this
<img width="665" alt="截屏2021-03-25 上午1 35 59" src="https://user-images.githubusercontent.com/54047796/112357502-8d047100-8d0a-11eb-829f-57841f1d8777.png">

the raster meets error looks like this one

![image](https://user-images.githubusercontent.com/54047796/112358338-38152a80-8d0b-11eb-8ec1-931a741fcdff.png)

**Comment by arielfri** [comment]
Latest update corrects this issue
